services:
  llamacpp:
    build: .
    container_name: llamacpp
    ports:
      - "11111:11111"
    volumes:
      - ./models:/models
      - ./config/:/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      ./llama.cpp/build/bin/llama-server --models-dir /models
      --port 11111
      --host 0.0.0.0
      --api-key 'very-secure-api-key'
      --models-preset /config/config.ini
      --models-max 1
